# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/itoledo/Work/gWTO2/gwto2.ui'
#
# Created: Sat Jun 28 23:42:38 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1090, 822)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.MainFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainFrame.sizePolicy().hasHeightForWidth())
        self.MainFrame.setSizePolicy(sizePolicy)
        self.MainFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.MainFrame.setObjectName(_fromUtf8("MainFrame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.MainFrame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.OptionsFrame = QtGui.QFrame(self.MainFrame)
        self.OptionsFrame.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OptionsFrame.sizePolicy().hasHeightForWidth())
        self.OptionsFrame.setSizePolicy(sizePolicy)
        self.OptionsFrame.setMinimumSize(QtCore.QSize(0, 30))
        self.OptionsFrame.setFrameShape(QtGui.QFrame.Box)
        self.OptionsFrame.setObjectName(_fromUtf8("OptionsFrame"))
        self.gridLayout_6 = QtGui.QGridLayout(self.OptionsFrame)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.pwv_label = QtGui.QLabel(self.OptionsFrame)
        self.pwv_label.setObjectName(_fromUtf8("pwv_label"))
        self.gridLayout_6.addWidget(self.pwv_label, 0, 2, 1, 1)
        self.maxha_spin = QtGui.QSpinBox(self.OptionsFrame)
        self.maxha_spin.setMinimum(-12)
        self.maxha_spin.setMaximum(12)
        self.maxha_spin.setProperty("value", 3)
        self.maxha_spin.setObjectName(_fromUtf8("maxha_spin"))
        self.gridLayout_6.addWidget(self.maxha_spin, 1, 5, 1, 1)
        self.date_datetime = QtGui.QDateTimeEdit(self.OptionsFrame)
        self.date_datetime.setCurrentSection(QtGui.QDateTimeEdit.YearSection)
        self.date_datetime.setTimeSpec(QtCore.Qt.UTC)
        self.date_datetime.setObjectName(_fromUtf8("date_datetime"))
        self.gridLayout_6.addWidget(self.date_datetime, 0, 1, 1, 1)
        self.horizon_spin = QtGui.QSpinBox(self.OptionsFrame)
        self.horizon_spin.setMaximum(90)
        self.horizon_spin.setProperty("value", 20)
        self.horizon_spin.setObjectName(_fromUtf8("horizon_spin"))
        self.gridLayout_6.addWidget(self.horizon_spin, 1, 1, 1, 1)
        self.minha_spin = QtGui.QSpinBox(self.OptionsFrame)
        self.minha_spin.setMinimum(-12)
        self.minha_spin.setMaximum(12)
        self.minha_spin.setProperty("value", -5)
        self.minha_spin.setObjectName(_fromUtf8("minha_spin"))
        self.gridLayout_6.addWidget(self.minha_spin, 1, 3, 1, 1)
        self.horizon_label = QtGui.QLabel(self.OptionsFrame)
        self.horizon_label.setObjectName(_fromUtf8("horizon_label"))
        self.gridLayout_6.addWidget(self.horizon_label, 1, 0, 1, 1)
        self.minha_label = QtGui.QLabel(self.OptionsFrame)
        self.minha_label.setObjectName(_fromUtf8("minha_label"))
        self.gridLayout_6.addWidget(self.minha_label, 1, 2, 1, 1)
        self.date_label = QtGui.QLabel(self.OptionsFrame)
        self.date_label.setObjectName(_fromUtf8("date_label"))
        self.gridLayout_6.addWidget(self.date_label, 0, 0, 1, 1)
        self.maxha_label = QtGui.QLabel(self.OptionsFrame)
        self.maxha_label.setObjectName(_fromUtf8("maxha_label"))
        self.gridLayout_6.addWidget(self.maxha_label, 1, 4, 1, 1)
        self.pwv_spin = QtGui.QDoubleSpinBox(self.OptionsFrame)
        self.pwv_spin.setReadOnly(False)
        self.pwv_spin.setMaximum(20.0)
        self.pwv_spin.setSingleStep(0.05)
        self.pwv_spin.setProperty("value", 1.2)
        self.pwv_spin.setObjectName(_fromUtf8("pwv_spin"))
        self.gridLayout_6.addWidget(self.pwv_spin, 0, 3, 1, 1)
        self.lst_label = QtGui.QLabel(self.OptionsFrame)
        self.lst_label.setObjectName(_fromUtf8("lst_label"))
        self.gridLayout_6.addWidget(self.lst_label, 0, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 7, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 1, 7, 1, 1)
        self.lst_spin = QtGui.QTimeEdit(self.OptionsFrame)
        self.lst_spin.setEnabled(True)
        self.lst_spin.setReadOnly(True)
        self.lst_spin.setObjectName(_fromUtf8("lst_spin"))
        self.gridLayout_6.addWidget(self.lst_spin, 0, 5, 1, 1)
        self.ArraysFrame = QtGui.QFrame(self.OptionsFrame)
        self.ArraysFrame.setMinimumSize(QtCore.QSize(400, 0))
        self.ArraysFrame.setAutoFillBackground(True)
        self.ArraysFrame.setFrameShape(QtGui.QFrame.Box)
        self.ArraysFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.ArraysFrame.setObjectName(_fromUtf8("ArraysFrame"))
        self.gridLayout_7 = QtGui.QGridLayout(self.ArraysFrame)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.array_label = QtGui.QLabel(self.ArraysFrame)
        self.array_label.setObjectName(_fromUtf8("array_label"))
        self.gridLayout_7.addWidget(self.array_label, 0, 0, 1, 1)
        self.antennas_spin = QtGui.QSpinBox(self.ArraysFrame)
        self.antennas_spin.setMinimum(20)
        self.antennas_spin.setMaximum(54)
        self.antennas_spin.setProperty("value", 34)
        self.antennas_spin.setObjectName(_fromUtf8("antennas_spin"))
        self.gridLayout_7.addWidget(self.antennas_spin, 1, 4, 1, 1)
        self.stdarrays_combo = QtGui.QComboBox(self.ArraysFrame)
        self.stdarrays_combo.setObjectName(_fromUtf8("stdarrays_combo"))
        self.stdarrays_combo.addItem(_fromUtf8(""))
        self.stdarrays_combo.addItem(_fromUtf8(""))
        self.stdarrays_combo.addItem(_fromUtf8(""))
        self.stdarrays_combo.addItem(_fromUtf8(""))
        self.stdarrays_combo.addItem(_fromUtf8(""))
        self.stdarrays_combo.addItem(_fromUtf8(""))
        self.stdarrays_combo.addItem(_fromUtf8(""))
        self.stdarrays_combo.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.stdarrays_combo, 1, 2, 1, 1)
        self.std_conf_label = QtGui.QLabel(self.ArraysFrame)
        self.std_conf_label.setObjectName(_fromUtf8("std_conf_label"))
        self.gridLayout_7.addWidget(self.std_conf_label, 1, 0, 1, 1)
        self.arrayAR_label = QtGui.QLabel(self.ArraysFrame)
        self.arrayAR_label.setObjectName(_fromUtf8("arrayAR_label"))
        self.gridLayout_7.addWidget(self.arrayAR_label, 0, 3, 1, 1)
        self.antennas_label = QtGui.QLabel(self.ArraysFrame)
        self.antennas_label.setObjectName(_fromUtf8("antennas_label"))
        self.gridLayout_7.addWidget(self.antennas_label, 1, 3, 1, 1)
        self.blarrays_combo = QtGui.QComboBox(self.ArraysFrame)
        self.blarrays_combo.setObjectName(_fromUtf8("blarrays_combo"))
        self.gridLayout_7.addWidget(self.blarrays_combo, 0, 2, 1, 1)
        self.array_ar_spin = QtGui.QDoubleSpinBox(self.ArraysFrame)
        self.array_ar_spin.setMinimum(0.01)
        self.array_ar_spin.setSingleStep(0.1)
        self.array_ar_spin.setProperty("value", 1.0)
        self.array_ar_spin.setObjectName(_fromUtf8("array_ar_spin"))
        self.gridLayout_7.addWidget(self.array_ar_spin, 0, 4, 1, 1)
        self.gridLayout_6.addWidget(self.ArraysFrame, 0, 12, 2, 1)
        self.now_button = QtGui.QPushButton(self.OptionsFrame)
        self.now_button.setObjectName(_fromUtf8("now_button"))
        self.gridLayout_6.addWidget(self.now_button, 0, 6, 1, 1)
        self.gridLayout_2.addWidget(self.OptionsFrame, 0, 0, 1, 1)
        self.TabFrame = QtGui.QFrame(self.MainFrame)
        self.TabFrame.setFrameShape(QtGui.QFrame.Box)
        self.TabFrame.setObjectName(_fromUtf8("TabFrame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.TabFrame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.TabFrame)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.bl_tab = QtGui.QWidget()
        self.bl_tab.setAccessibleName(_fromUtf8(""))
        self.bl_tab.setObjectName(_fromUtf8("bl_tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.bl_tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.bl_sheet = QtGui.QTableView(self.bl_tab)
        self.bl_sheet.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.bl_sheet.setDragEnabled(True)
        self.bl_sheet.setSortingEnabled(True)
        self.bl_sheet.setObjectName(_fromUtf8("bl_sheet"))
        self.gridLayout_4.addWidget(self.bl_sheet, 0, 0, 1, 1)
        self.tabWidget.addTab(self.bl_tab, _fromUtf8(""))
        self.tc_tab = QtGui.QWidget()
        self.tc_tab.setObjectName(_fromUtf8("tc_tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tc_tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tc_sheet = QtGui.QTableView(self.tc_tab)
        self.tc_sheet.setObjectName(_fromUtf8("tc_sheet"))
        self.gridLayout_5.addWidget(self.tc_sheet, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tc_tab, _fromUtf8(""))
        self.pol_tab = QtGui.QWidget()
        self.pol_tab.setObjectName(_fromUtf8("pol_tab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.pol_tab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.pol_sheet = QtGui.QTableView(self.pol_tab)
        self.pol_sheet.setObjectName(_fromUtf8("pol_sheet"))
        self.gridLayout_8.addWidget(self.pol_sheet, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pol_tab, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.TabFrame, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.MainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.actionBL_Array = QtGui.QAction(MainWindow)
        self.actionBL_Array.setObjectName(_fromUtf8("actionBL_Array"))
        self.actionACA_Array = QtGui.QAction(MainWindow)
        self.actionACA_Array.setObjectName(_fromUtf8("actionACA_Array"))
        self.actionAll_SBs = QtGui.QAction(MainWindow)
        self.actionAll_SBs.setObjectName(_fromUtf8("actionAll_SBs"))
        self.actionPlanning = QtGui.QAction(MainWindow)
        self.actionPlanning.setObjectName(_fromUtf8("actionPlanning"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuMenu.addAction(self.actionBL_Array)
        self.menuMenu.addAction(self.actionACA_Array)
        self.menuMenu.addAction(self.actionAll_SBs)
        self.menuMenu.addAction(self.actionPlanning)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pwv_label.setText(_translate("MainWindow", "PWV", None))
        self.date_datetime.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd HH:mm", None))
        self.horizon_label.setText(_translate("MainWindow", "Horizon", None))
        self.minha_label.setText(_translate("MainWindow", "minHA", None))
        self.date_label.setText(_translate("MainWindow", "Date", None))
        self.maxha_label.setText(_translate("MainWindow", "maxHA", None))
        self.lst_label.setText(_translate("MainWindow", "LST", None))
        self.array_label.setText(_translate("MainWindow", "Array:", None))
        self.stdarrays_combo.setItemText(0, _translate("MainWindow", "Current", None))
        self.stdarrays_combo.setItemText(1, _translate("MainWindow", "C34-1", None))
        self.stdarrays_combo.setItemText(2, _translate("MainWindow", "C34-2", None))
        self.stdarrays_combo.setItemText(3, _translate("MainWindow", "C34-3", None))
        self.stdarrays_combo.setItemText(4, _translate("MainWindow", "C34-4", None))
        self.stdarrays_combo.setItemText(5, _translate("MainWindow", "C34-5", None))
        self.stdarrays_combo.setItemText(6, _translate("MainWindow", "C34-6", None))
        self.stdarrays_combo.setItemText(7, _translate("MainWindow", "C34-7", None))
        self.std_conf_label.setText(_translate("MainWindow", "Std. Conf.:", None))
        self.arrayAR_label.setText(_translate("MainWindow", "Array AR", None))
        self.antennas_label.setText(_translate("MainWindow", "Antennas", None))
        self.now_button.setText(_translate("MainWindow", "Now", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bl_tab), _translate("MainWindow", "Tab 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tc_tab), _translate("MainWindow", "Tab 2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pol_tab), _translate("MainWindow", "Page", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.actionBL_Array.setText(_translate("MainWindow", "BL Array", None))
        self.actionACA_Array.setText(_translate("MainWindow", "ACA/TP Array", None))
        self.actionAll_SBs.setText(_translate("MainWindow", "All SBs", None))
        self.actionPlanning.setText(_translate("MainWindow", "Planning", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

